### PR TITLE
update to use .index_max()

### PR DESCRIPTION
**Pull request by conradsnicta**
related to PR https://github.com/mlpack/mlpack/pull/3835

### CODE REVIEW

**Review by eddelbuettel — CHANGES_REQUESTED** [review]
This retains a warning.  The point is to get rid of warnings as much as we can:

```
/home/edd/git/mlpack/src/mlpack/methods/perceptron/perceptron_impl.hpp:228:32: warning: unused variable ‘maxIndexCol’ [-Wunused-variable]
  228 |   arma::uword maxIndexRow = 0, maxIndexCol = 0;
      |                                ^~~~~~~~~~~
```

**Comment by conradsnicta** [comment]
@eddelbuettel I'm bandwidth constrained, so feel free to edit this PR, or merge and adapt further as you see fit.

**Comment by eddelbuettel** [comment]
> so feel free to edit this PR,

GitHub usually indicates when I can, and this feature is on by default.  I do not see it here. So in short: I can't.

**Comment by eddelbuettel** [comment]
The commit https://github.com/eddelbuettel/mlpack/pull/1/commits/9ed1f4b04d14cc69d6f6f7a516e39482d5fea432 is now part of the PR 3835 so this is take care of.

**Pull request closed without merging**
